---
#
# This is the "master" schema, which validates the format of the runtime
# schemas. Its purpose is to turn a runtime schema syntax error into a
# compile-time one.
#
$schema: http://json-schema.org/draft-07/schema#
title: Sensor data description
type: object
required:
  - id
  - name
  - data
properties:
  id:
    description: A sensor's ID, unique among all possible sensors
    type: string
    pattern: "^0x[a-z0-9]{8}$" # 32-bit hex
  name:
    description: A sensor's friendly name, which will be advertised to consumers
    type: string
    minLength: 1
    maxLength: 32
  data:
    type: array
    # It's useful for the parsing code to have a maximum number of entries it can
    # see.
    minItems: 1
    maxItems: 100
    items:
      type: object
      required:
        - name
        - unit
        - type
        - len
      properties:
        name:
          description: A description of the datapoint
          type: string
        unit:
          $ref: include://si-unit.yaml
        type:
          $ref: include://type.yaml
          type: integer
          minimum: 0
        len:
          description: The length of this entry
          oneOf:
            -
              type: integer
              minimum: 1
            -
              type: string
              const: all
