---
#
# This is the "master" schema, which validates the format of the runtime
# schemas. Its purpose is to turn a runtime schema syntax error into a
# compile-time one.
#
$schema: http://json-schema.org/draft-07/schema#
title: Sensor data description
type: object
required:
  - init
  - data
additionalProperties: false
properties:
  init:
    oneOf:
      - type: array
        items:
          $ref: include://type.yaml
      - type: "null"

  data:
    type: array
    items:
      type: object
      required:
        - id
        - name
        - fmt
      additionalProperties: false
      properties:
        id:
          description: A sensor's hound data ID, which must either match what's encoded in header files or be programatically generateable (e.g. OBD-II)
          type: integer
          minimum: 0
          maximum: 0xffffffff
        name:
          description: A sensor's friendly name, which will be advertised to consumers
          type: string
          minLength: 1
        fmt:
          type: array
          # It's useful for the parsing code to have a maximum number of entries it can
          # see.
          minItems: 1
          maxItems: 100
          items:
            type: object
            required:
              - name
              - unit
              - type
            properties:
              name:
                description: A description of the datapoint
                type: string
              unit:
                $ref: include://si-unit.yaml
              type:
                $ref: include://type.yaml
                type: integer
                minimum: 0
              len:
                description: The length of this entry
                oneOf:
                  -
                    type: integer
                    minimum: 1
                  -
                    type: string
                    const: all
