#!/bin/bash

set -uo pipefail

check_schema() {
    local schema="$1"
    local data="$2"

    if [[ ! -f $data ]]; then
        return
    fi
    if [[ $data == $schema ]]; then
        return
    fi

    CMD=""$MESON_SOURCE_ROOT/scripts/schema-check" \
             -s "$schema" \
             "$data""
    $CMD
    if [[ $? != 0 ]]; then
        echo "FAILED: $CMD" >&2
        exit 1
    fi
}

# Check for sschema, needed for schema checking.
python3 -c "import sschema"
if [[ $# != 0 ]]; then
    echo 'Cannot import python module sschema. Please run "pip3 install sschema"' >&2
fi

for datafile in "$MESON_SOURCE_ROOT"/schema/driver/deploy/*; do
    check_schema "$MESON_SOURCE_ROOT/schema/driver/meta/schema.yaml" "$datafile"
done
for datafile in "$MESON_SOURCE_ROOT"/test/config/*; do
    check_schema "$MESON_SOURCE_ROOT/schema/config/meta/schema.yaml" "$datafile"
done
for datafile in "$MESON_SOURCE_ROOT"/test/schema/*; do
    check_schema "$MESON_SOURCE_ROOT/schema/driver/meta/schema.yaml" "$datafile"
done
